"""analysis_artifacts (RF-041/RF-042)

Revision ID: 09548dad28a4
Revises: 52ab1110c67c
Create Date: 2026-08-15 22:45:19.954928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09548dad28a4'
down_revision: Union[str, Sequence[str], None] = '52ab1110c67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('CHART', name='artifact_type'), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_sql', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_artifacts_analysis_id'), 'analysis_artifacts', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_artifacts_analysis_id'), table_name='analysis_artifacts')
    op.drop_table('analysis_artifacts')
    # ### end Alembic commands ###

    # Autogenerate no genera el DROP TYPE del enum inline creado por
    # create_table (mismo gotcha ya visto en migraciones anteriores).
    sa.Enum(name='artifact_type').drop(op.get_bind(), checkfirst=True)
