"""agent: analyses, agent_runs, tool_calls

Revision ID: 12b60fee556a
Revises: 6fa5793b97eb
Create Date: 2026-08-15 20:09:58.526343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b60fee556a'
down_revision: Union[str, Sequence[str], None] = '6fa5793b97eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PLANNING', 'TOOL_RUNNING', 'ANALYZING', 'GENERATING_RESPONSE', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT', name='analysis_status'), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_dataset_id'), 'analyses', ['dataset_id'], unique=False)
    op.create_index('ix_analyses_org_created_at', 'analyses', ['organization_id', 'created_at'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='agent_run_status'), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_analysis_id'), 'agent_runs', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_trace_id'), 'agent_runs', ['trace_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', name='tool_call_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_agent_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_agent_runs_trace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_analysis_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_analyses_org_created_at', table_name='analyses')
    op.drop_index(op.f('ix_analyses_dataset_id'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
    # create_table con Enum inline crea implicitamente el tipo Postgres -
    # autogenerate no lo agrega al downgrade (mismo gotcha que la
    # migracion ad67c44f87a7 con membership_role). Sin esto, upgrade ->
    # downgrade -> upgrade rompe con "type already exists".
    sa.Enum(name='tool_call_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='agent_run_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='analysis_status').drop(op.get_bind(), checkfirst=True)
