"""analyses arq_job_id y agent_run_status cancelled

Revision ID: 52ab1110c67c
Revises: e98609a5a5db
Create Date: 2026-08-15 21:52:53.910189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ab1110c67c'
down_revision: Union[str, Sequence[str], None] = 'e98609a5a5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('arq_job_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate no detecta valores nuevos de un tipo ENUM existente
    # (limitacion conocida de Alembic) - agregado a mano. RF-025: el agent
    # run necesita poder quedar en CANCELLED, no solo RUNNING/COMPLETED/FAILED.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE agent_run_status ADD VALUE IF NOT EXISTS 'CANCELLED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'arq_job_id')
    # ### end Alembic commands ###

    # Postgres no soporta DROP VALUE de un ENUM directamente - se recrea el
    # tipo sin 'CANCELLED'. Falla si alguna fila todavia tiene ese status
    # (comportamiento esperado de un downgrade, mismo criterio que otras
    # migraciones de este proyecto que documentan perdida de datos al bajar).
    op.execute("ALTER TYPE agent_run_status RENAME TO agent_run_status_old")
    op.execute("CREATE TYPE agent_run_status AS ENUM ('RUNNING', 'COMPLETED', 'FAILED')")
    op.execute(
        "ALTER TABLE agent_runs ALTER COLUMN status TYPE agent_run_status "
        "USING status::text::agent_run_status"
    )
    op.execute("DROP TYPE agent_run_status_old")
