"""hardening: constraints e indices tras code review

Revision ID: 6fa5793b97eb
Revises: 8476c3ae762d
Create Date: 2026-08-15 19:14:50.809267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa5793b97eb'
down_revision: Union[str, Sequence[str], None] = '8476c3ae762d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.create_index('ix_audit_events_org_created_at', 'audit_events', ['organization_id', 'created_at'], unique=False)
    op.drop_constraint(op.f('audit_events_actor_id_fkey'), 'audit_events', type_='foreignkey')
    op.create_foreign_key(
        'audit_events_actor_id_fkey', 'audit_events', 'users', ['actor_id'], ['id'],
        ondelete='RESTRICT',
    )
    op.alter_column('data_sources', 'secret_ref',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint('uq_data_source_org_type', 'data_sources', ['organization_id', 'type'])
    op.drop_index(op.f('ix_datasets_organization_id'), table_name='datasets')
    op.create_index('ix_datasets_org_created_at', 'datasets', ['organization_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.drop_index('ix_datasets_org_created_at', table_name='datasets')
    op.create_index(op.f('ix_datasets_organization_id'), 'datasets', ['organization_id'], unique=False)
    op.drop_constraint('uq_data_source_org_type', 'data_sources', type_='unique')
    op.alter_column('data_sources', 'secret_ref',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint('audit_events_actor_id_fkey', 'audit_events', type_='foreignkey')
    op.create_foreign_key(op.f('audit_events_actor_id_fkey'), 'audit_events', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_audit_events_org_created_at', table_name='audit_events')
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    # ### end Alembic commands ###
