"""data_sources conexion externa postgres

Revision ID: e98609a5a5db
Revises: 12b60fee556a
Create Date: 2026-08-15 21:16:10.567864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98609a5a5db'
down_revision: Union[str, Sequence[str], None] = '12b60fee556a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('data_sources', sa.Column('host', sa.String(length=255), nullable=True))
    op.add_column('data_sources', sa.Column('port', sa.Integer(), nullable=True))
    op.add_column('data_sources', sa.Column('database_name', sa.String(length=200), nullable=True))
    op.add_column('data_sources', sa.Column('username', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'username')
    op.drop_column('data_sources', 'database_name')
    op.drop_column('data_sources', 'port')
    op.drop_column('data_sources', 'host')
    op.drop_column('data_sources', 'name')
    # ### end Alembic commands ###
